//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Johnson_Ryan_1310903
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int GUID { get; set; }
        public int MatricNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompA { get; set; }
        public string CompB { get; set; }
        public string CompC { get; set; }
        public string FinalGrade { get; set; }

    }
}
